//
//  _strings[.swift
//  CarrifreeStorage
//
//  Created by plattics-kwon on 2020/12/28.
//



// #########################################
//
//     !!! 번역 작업 전 반드시 확인해주세요 !!!
//
//  캐리프리 보관앱 텍스트 파일입니다.
//  영어로 번역하실때
//  var en: String {
//  이 문장을 검색하셔서
//  그 밑으로 나오는 모든 한글 text들을 번역해주시면 됩니다.
//  ("" 안의 한글 대신 번역된 text를 입력해주세요)
//  궁금한점 있으시면 언제든 연락해주세요!
//
// #########################################




import Foundation

typealias _strings = MyStrings

enum MyStrings: String {
    
    static subscript(_ string: MyStrings) -> String {
        return string.rawValue
    }
    
    case ok = "확인"
    case cancel = "취소"
    case yes = "네"
    case no = "아니오"
    case id = "아이디"
    case pw = "비밀번호"
    case findIDPW = "ID/비밀번호 찾기"
    case camera = "카메라"
    case signIn = "로그인"
    case signOut = "로그아웃"
    case signOutDone = "로그아웃 되었습니다"
    case signUp = "회원가입"
    case address = "주소"
    case searchAddress = "주소 찾기"
    case photo = "사진"
    case photoAlbum = "사진 앨범"
    case setMyInfo = "내 정보 변경"
    case copied = "복사 됨"
    case service = "서비스"
    case serviceRequestDate = "서비스 신청 일시"
    case storeService = "보관 서비스"
    case entrust = "맡김"
    case take = "찾음"
    case findId = "아이디 찾기"
    case findPw = "비밀번호 찾기"
    case findByEmail = "이메일로 찾기"
    case findByPhoneNum = "휴대폰 번호로 찾기"
    case storageOperAgree = "보관사업자 약관동의"
    case showTerms = "약관 보기"
    case save = "저장"
    case modify = "수정"
    case saveDone = "저장되었습니다"
    case saveFailed = "저장 실패"
    case plzTryAgain = "다시 시도해주시기 바랍니다"
    case registerWith01 = "로 등록"
    case registerWith02 = "으로 등록"
    case defaultCost = "기본요금"
    case extraCost = "추가요금"
    case size = "사이즈"
    case bizName = "상호명"
    case memberInfo = "회원 정보"
    case bizCategory = "업종"
    case bizNo = "사업자 번호"
    case bizLicense = "사업자 등록증"
    case name = "이름"
    case name2 = "성명"
    case startTime = "맡기는 시간"
    case endTime = "찾는 시간"
    case duringTotal = "총 보관 시간"
    case driver = "운송자"
    case customer = "고객"
    case completion = "완료"
    case storageInfo = "보관장소 정보"
    case eMail = "이메일"
    case bankAccountNum = "계좌번호"
    case addressDetail = "상세주소"
    case enterAddressDetail = "상세주소 입력"
    case introduceInfoText = "소개글"
    case introduceInfoTextPlaceHolder = "상호 밑에 사업자의 소개부분에 들어갈 내용입니다. 서비스의 내용, 특징 등 고객에게 어필할 내용을 작성해보세요."
    case workTime = "활동 시간"
    case selectBank = "은행 선택"
    case registerDayOffDefault = "기본(토, 일, 국경일)"
    case registerDayOffManual = "수동선택(중복선택 가능)"
    case registerDayOffAllHoliday = "국경일 모두 쉬기"
    case annouceBusiness = "물품 보관/위수탁 사업 안내"
    case storageDesc = "짐 보관 장소의 역할로 매출액의 70%(제세공과금 정산 후)가 정산됩니다"
    case consignmentStore = "위수탁 창구"
    case consignmentStoreDesc = "운반 의뢰 고객이 짐맡김/찾음 장소 중 한 곳으로 지정시 해당 짐맡김/찾음 창구사용료 중 60%(제세공과금 정산 후)가 지급됩니다."
    case cost = "가격"
    case cost2 = "금액"
    case cost3 = "결제금액"
    case cost4 = "추가금액"
    case cost5 = "총 금액"
    case cost6 = "환불금액"
    case cost7 = "정산금액"
    case costDesc = "보관 가격은 기본적으로 캐리프리에서 시세를 반영한 값을 제시합니다. 제시된 가격의 -50% ~ +50% 내에서 가격을 조정할 수 있습니다."
    case seeMore = "더보기"
    case luggageInfo = "짐정보"
    case requests = "요청사항"
    case startStorage = "보관 시작"
    case endStorage = "보관 종료"
    case consignment = "위수탁"
    case storageRequestIsEmpty = "보관 의뢰가 없습니다"
    case carrierBaseRequestIsEmpty = "위수탁 의뢰가 없습니다"
    case someonesReqeust = "[%@]님의 의뢰내용"
    case someonesStartCarrierBaseRequest = "[%@]님의 의뢰내용\n(물품 보관 후 운반 위탁)"
    case someonesEndCarrierBaseRequest = "[%@]님의 의뢰내용\n(운반된 물품 보관 후 고객에게 전달)"
    case callToSomeone = "[%@] 님에게 전화하시겠습니까?"
    case storage = "보관"
    case inDelivery = "이동 중"
    case arrival = "도착"
    case cannotVerified = "'%@'을(를) 확인할 수 없습니다"
    case sendLuggage = "물품 반출"
    case totalSales = "총 매출"
    case annualSales = "연 매출"
    case monthlySales = "월 매출"
    case dailySales = "일 매출"
    case sales = "매출액"
    case profit = "수령금액"
    case excelDownloadDesc = "세부 매출 내용은 엑셀 파일로 다운로드할 수 있습니다"
    case excelDownload = "엑셀 파일 다운로드"
    case ordered = "접수"
    case requestSuccess = "요청 성공"
    case requestFailed = "요청 실패"
    case customerName = "고객 이름"
    case requestType = "의뢰 방법"
    case reply = "댓글"
    case verificationFailed01 = "본인인증에 실패했습니다"
    case verificationFailed02 = "인증 실패"
    case verificationSuccess01 = "본인인증 성공"
    case verificationSuccess02 = "인증 성공"
    case failedToWithdrawal = "회원 탈퇴 실패"
    case successToWithdrawal = "회원 탈퇴가 완료되었습니다"
    case withdrawal = "회원 탈퇴"
    case needSignIn = "로그인이 필요합니다"
    case csAnnounce = "문의 메일 주소가 복사되었습니다.해당 메일 주소로 문의 내용을 보내주시기 바랍니다.\n감사합니다."
    case requestList = "의뢰 목록"
    case noReviews = "작성된 평가가 없습니다"
    case needBizInfo = "먼저 [기본 정보]를 입력해주세요"
    case registerCost = "가격등록"
    case mustRegisterToRecieveRequest = "아래 정보를 모두 등록해야 의뢰를 받을 수 있습니다"
    case touchAndRegisterInfo = "터치하여 정보 등록"
    case todayExpectedSales = "오늘 예상 매출"
    case thisMonthSales = "이번달 매출"
    case reservationDate = "예약일"
    case during = "보관시간"
    case luggageCount = "짐 갯수"
    case requiredAppUpdate = "앱 업데이트가 필요합니다"
    case moveToStore = "스토어로 이동"
    case accountHolder = "예금주명"
    case businessApproval = "사업자 승인"
    case waitingBusinessApproval = "사업자 승인 대기중"
    case registerStoragePictures = "보관장소 사진 등록"
    case pictureStorageFrontBack = "보관장소 전면/후면 사진 1장이상"
    case pictureStorageNormal = "보관장소 사진 1장이상"
    case pictureStorageMain = "메인으로 표시할 사진\n(보관소 전면 사진을 등록해주세요)"
    case registration = "등록"
    case socialAccountDesc = "소셜 로그인(%@) 계정입니다"
    case searchStorageRequest = "보관 의뢰 검색"
    case searchCarrierBaseRequest = "위수탁 의뢰 검색"
    case search = "검색"
    case requestNo = "주문번호"
    case passwordRule = "필수: 6~12자리 영문, 숫자, !@#$%^&*"
    case passwordCheck = "비밀번호 확인"
    case registrationComplete = "등록 완료"
    case changePassword = "비밀번호 변경"
    case enterBankAccountInfo = "계좌 정보 입력"
    case bank = "은행"
    case contactNum = "연락처"
    case contactNumOther = "비상 연락처"
    case required = "필수"
    case horizontal = "가로"
    case vertical = "세로"
    case height = "높이"
    case signUpEmail = "회원가입시 작성한 이메일"
    case emailVerificationCode = "이메일로 발송된 인증 코드"
    case verificationCode = "인증 코드"
    case sendVerificationCode = "인증 코드 발송"
    case needNewPw = "비밀번호가 기억나지 않으면 새비밀번호를 설정해야합니다."
    case signInWithSNSAccount = "SNS 계정으로 로그인"
    case normalSignUp = "일반(캐리프리) 회원가입"
    case chooseSignUp = "가입 방식 선택"
    case terms = "이용 약관"
    case see = "보기"
    case duplicationCheck = "중복 확인"
    case recommedCode = "추천 코드"
    case optional = "선택 사항"
    case send = "발송"
    case verification = "인증"
    case userCode = "유저 코드"
    case dayInCostTitle = "1일 이내 요금"
    case dayInCostDesc01 = "기본요금: 4시간 / 추가요금: 1시간"
    case dayInCostDesc02 = "(처음 4시간 기본 요금 적용 후 1시간당 추가요금 발생)"
    case dayOverCostTitle = "1일 이후 요금"
    case dayOverCostDesc = "처음 보관한 시간으로부터 24시간이 지난 후 1일 단위로 발생하는 요금"
    case carrifreeCostTtile = "가격 설정 기준"
    case extraCostDesc01 = "고객이 의뢰 종료 시간보다 늦게 물품을 찾으러 오는 경우 책정한 보관 비용에 따라 초과된 금액을 고객에게 요청할 수 있습니다. 캐리프리는 초과금에 대해 앱을 통한 추가 결제를 유도하지 않으므로 고객에게 현금 또는 보관소내 결제 단말기(POS, 캐리프리 키오스크 등)를 통해 초과금 지급을 요구해 주시기 바랍니다."
    case extraCostDesc02 = "위수탁 창구 역할로 짐을 맡은 경우 물품이 1일이내에 반출되면 보관 비용을 별도로 청구할 수 없습니다. 1일을 경과하는 경우 책정한 보관비용에 따라 초과된 금액을 고객에게 요청할 수 있습니다."
    case extraCostTitle = "초과 금액이 발생한 경우"
    case storagePicture = "보관소 사진"
    case holiday = "쉬는날"
    case storageCost = "보관 단가"
    case bizInfo = "사업자 정보"
    case review = "리뷰"
    case settings = "설정"
    case orderStatusPurchasedDesc = "보관이 진행되면 ‘보관중’으로 넘어갑니다.\n완료 또는 취소된 보관 내용은 ‘처리완료’로 넘어갑니다."
    case orderStatusEntrustDesc = "보관이 완료되면 ‘처리완료’로 넘어갑니다.\n초과 발생금액은 직접 정산하시기 바랍니다."
    case orderStatusTakeDesc = "처리가 완료된 내역을 표시합니다."
    case orderStatusPurchasedTitle = "주문대기"
    case orderStatusEntrustTitle = "보관중"
    case orderStatusTakeTitle = "처리완료"
    case runAgain = "앱을 종료한 후 다시 실행해주시기 바랍니다."
    case socialSignInFailed = "소셜 계정 로그인 실패"
    case changeBizInfo = "사업자 정보 변경"
    case helloCarrifree = "안녕하세요.\n캐리프리입니다."
    case needCarrifreeStorageSignIn = "보관파트너 전용 서비스를 위해 로그인 해주세요."
    case bizInfoChanged = "사업자 정보가 변경되었습니다."
    case approvalRequestDone = "보관 파트너 승인을 요청했습니다.\n감사합니다."
    case meritsPlaceholder = "매장의 특별한 점이 있다면 적어주세요."
    case canChangePw = "비밀번호를 변경할 수 있습니다."
    case thisMonthSalesTitle = "이번달 수입은\n%@\n입니다."
    case seeDetail = "상세내역보기"
    case needRegistrationTitle = "아직 업체 정보가 등록되지 않았습니다.\n정보입력 후 활동이 가능합니다."
    case registerInfo = "정보 등록하기"
    case guide = "이용 안내"
    case guideDesc = "캐리프리 보관파트너를 위한 앱\n이렇게 사용해 보세요!"
    case salesDetailBtnTitle = "상세내역은 아래 버튼을 눌러 확인하세요."
    case writeBizInfo = "사업자정보 입력"
    case writeName = "이름 입력"
    case nameWarning = "불건전한 업체 이름은 승인처리가안될 수 있습니다."
    case contactOption = "‘-’를 제외하고 숫자만 입력"
    case requestAuth = "인증요청"
    case authNo = "인증번호"
    case checkAuth = "인증 확인"
    case authComplete = "인증완료"
    case postalCode = "우편번호"
    case findPostalCode = "우편번호찾기"
    case bizAddress = "사업장 주소"
    case bankAccountDesc = "계좌번호 (‘-’없이 입력)"
    case needFile = "제출서류를 제출해주세요."
    case addBizLicense = "사업자등록증 추가"
    case addBizLicenseDesc = "최근 발급일 6개월 이내"
    case addBankbook = "통장사본 추가"
    case addBankbookDesc = "입력하신 계좌와 동일한 통장사본"
    case beforeRegistration = "등록 전 확인해주세요."
    case beforeRegistrationDesc = """
    ・ 타인의 명의로 가입한 경우 승인처리가 완료되지
       않습니다.
    ・ 한번 승인 된 사업자 및 결제정보를 변경 할 경우
       다시 재심사를 진행하여야 합니다.
    """
    case registrationWating = "최대 5분이내에 처리 완료 될 예정입니다."
    case requestRegistration = "보관파트너 승인 요청"
    case validLicneseNo = "유효한 사업자등록번호 입니다."
    case enterStoreInfo = "매장정보 입력"
    case setVisible = "보관사업자 게시 상태 설정"
    case visible = "노출"
    case invisible = "비노출"
    case visibleDesc = "영업이 바쁘거나 갑작스럽게 영업이 어려운 경우 ‘비노출’로 설정하시면 사용자앱에서 검색시 노출되지 않습니다."
    case registerStorePic = "매장사진을 등록해주세요.(최대 10개)"
    case registerStorePicDesc = "버튼을 눌러 매장사진을 등록하세요. 대표사진 1개는 등록되어야 매장 정보를 노출시킬 수 있습니다."
    case registerStoreInfo = "매장정보 등록/수정"
    case registerWorkTime = "매장 운영시간을 등록해주세요."
    case opentime = "시작시간"
    case closetime = "종료시간"
    case enterPr = "매장 소개글을 적어주세요."
    case enterLuggagesTitle = "짐 보관은 최대 몇개까지 가능하신가요?"
    case enterLuggages = "보관 가능한 짐 개수를 입력해주세요"
    case wrongLuggages = "짐 보관 수량을 올바르게 입력해주세요."
    case ea = "개"
    case enterMerits = "보관 장점을 선택하세요."
    case emptyMerits = "보관 장점을 1개 이상 선택해주세요"
    case enterCosts = "보관가격을 설정해주세요."
    case usingCarrifreeCosts = "캐리프리 시세 반영"
    case needDefaultSotrePic = "업체(매장) 사진을 1장 이상 등록해주세요"
    case wrongWorktime = "근무 시간을 올바르게 입력해주세요"
    case wrongCosts = "가격을 올바르게 설정해주세요."
    case registerStore = "매장정보 등록"
    case needPhotoAccessPermission = "사진 접근 권한이 필요합니다. '확인'을 선택하면 사진 접근 설정 화면으로 이동합니다."
    case notApproved = "미승인"
    case approvalComplete = "승인완료"
    case orderBegin = "짐보관\n서비스가\n시작되었습니다."
    case orderBeginDesc = "짐보관 서비스가 시작되었으며, 진행중인 내역은 메뉴바 ‘보관중’에서 다시 확인하실 수 있습니다."
    case orderComplete = "짐보관\n서비스가\n완료되었습니다."
    case orderCompleteDesc = "짐보관이 완료되었료습니다. 완료된 주문내역은 [처리완료]에서 다시 확인이 가능합니다."
    case moveToRegistration = "사업자/매장 정보 입력하기"
    case backToContent = "다시 확인"
    case notYetDesc = "파트너님은\n서비스 이용을\n할 수 없습니다."
    case askOrderCheck = "파트너님\n주문서를 확인\n하셨나요?"
    case needOrderCheck = "고객의 정보와 보관할 짐의 이미지가 주문서와 일치하는지 다시 한번 확인 해주시기 바랍니다."
    case goOrder = "보관 진행"
    case orderDone = "보관 완료"
    case canceledOrder = "취소된 주문입니다."
    case vat = "부가세 포함"
    case payDirect = "직접정산"
    case refundDone = "환불완료"
    case autoRefund = "자동환불"
    case whoOrdered = "주문자"
    case hour = "시간"
    case all = "전체"
    case enterNameOrOrderNo = "'고객명' 혹은 '주문번호' 입력."
    case wrongOrderInfo = "잘못된 의뢰 정보입니다."
    case cashup = "정산"
    case showList = "목록보기"
    case orderCount = "보관건수"
    case salesDuration = "매출기준"
    case cashupInfo = "정산내역"
    case selectMonth = "월 선택"
    case duration = "기간"
    case storeInfo = "매장 정보"
    
    case alertSendEmailVerificationCode = "이메일로 인증 코드가 발급되었습니다. 확인 후 인증 코드를 입력해주시기 바랍니다."
    case alertRetryAddress = "주소 찾기에서 오류가 발생했습니다. 다시 시도해주시기 바랍니다."
    case alertNotFountLatLng = "주소와 일치하는 위도/경도 좌표를 찾지 못했습니다. 다시 시도해주시기 바랍니다."
    case alertSelectBank = "은행을 선택해주세요"
    case alertSelectStoreCategory = "업종을 선택해주세요"
    case alertEnterBizName = "업체명을 입력해주세요"
    case alertEnterBizAddress = "사업장 주소를 입력해주세요"
    case alertEnterAddressDetail = "상세주소를 입력해주세요"
    case alertEnterBizNo = "사업자등록번호를 입력해주세요"
    case alertEnterBankAccount = "정산받을 계좌번호를 입력해주세요"
    case alertEnterPhone = "연락처를 입력해주세요"
    case alertSelectPicture = "사진을 선택해주세요"
    case alertFailedToLoadCost = "요금 정보를 받아오지 못했습니다"
    case alertCannotYetStorage = "아직 보관할 수 없습니다"
    case alertCannotYetSend = "아직 반출할 수 없습니다"
    case alertAcceptRequest = "[%@]님의 의뢰를 수락하시겠습니까?"
    case alertSendLuggage = "[%@]님에게 물품을 전달하시겠습니까?"
    case alertCannotCheckUserPw = "고객님의 비밀번호를 확인할 수 없습니다"
    case alertFailedToLoadReview = "리뷰를 불러오지 못했습니다"
    case alertFailedToRegisterReply = "댓글을 등록하지 못했습니다"
    case alertWithdrawal = "회원 탈퇴시 모든 정보가 삭제되며,\n이후 복구가 불가능합니다\n탈퇴를 진행하시겠습니까?"
    case alertNeedAgreeForChangePw = "핸드폰 번호를 변경하려면 [%@]에 동의해주시기 바랍니다"
    case alertAskChangePhone = "핸드폰 번호를 변경하시겠습니까?"
    case alertNeedTerms02 = "개인정보 처리방침에 동의해주시기 바랍니다"
    case alertLoadBasicCostFailed = "기본 가격 정보를 불러오지 못했습니다."
    case alertLoadCostFailed = "내 가격 정보를 불러오지 못했습니다."
    case alertRegisterCostSuccess = "보관 가격 등록 완료"
    case alertRegisterCostFailed = "가격을 등록하지 못했습니다"
    case alertUpdateInfoLoadFailed = "업데이트 정보를 불러오지 못했습니다."
    case alertEnterAccountHolder = "예금주명을 입력해주세요"
    case alertRequestApproval = """
    아직 캐리프리 사업자로 승인되지 않았습니다.
    
    [기본 정보]
    [보관소 사진]
    [쉬는날]
    [보관 단가]
    
    항목을 모두 입력해야 사업자 승인이 이루어집니다. 승인은 1~2일이 소요되며 승인이 완료된 후 고객의 보관 의뢰를 받을 수 있습니다.
    """
    case alertIncorrectPasswordLength = "비밀번호는 6자 이상 12자 이하여야 합니다"
    case alertNeedAlphabet = "영문이 1개 이상 포함되어야 합니다"
    case alertNeedNumber = "숫자가 1개 이상 포함되어야 합니다"
    case alertNeedSpecialChar = "특수문자가 1개 이상 포함되어야 합니다"
    case alertPasswordAvailable = "사용 가능한 비밀번호입니다"
    case alertNoAvailableId = "가입할 수 없는 ID 입니다"
    case alertSuccessToSendCode = "코드 발급 성공"
    case alertFailedToSendCode = "코드 발급 실패"
    case alertSuccessToFindId = "아이디 찾기 성공"
    case alertNeedId = "아이디를 입력해주세요"
    case alertNeedEmail = "이메일을 입력해주세요"
    case alertNeedVerificationCode = "인증 번호를 입력해주세요"
    case alertNeedPw = "비밀번호를 입력해주세요"
    case alertPwNotMatch = "비밀번호가 일치하지 않습니다"
    case alertChangePwComplete = "비밀번호 변경 완료"
    case alertFailedToChangePw = "비밀번호를 변경하지 못했습니다"
    case alertSignInFailed = "로그인 실패"
    case alertSignInSuccess = "로그인 성공"
    case alertWelcome = "%@님 환영합니다  : )"
    case alertAskSignIn = "%@ 아이디로 로그인하시겠습니까?"
    case alertIdLengthMin = "아이디는 최소 5자 이상이어야 합니다"
    case alertAvailableId = "사용 가능한 아이디입니다"
    case alertNeedName = "이름을 입력해주세요"
    case alertNeedIdDuplicationCheck = "아이디 중복 확인이 필요합니다"
    case alertUnavailablePw = "사용할 수 없는 비밀번호 입니다"
    case alertNeedEmailVerification = "이메일 인증을 진행해주세요"
    case alertNeedAgreeAllTerms = "모든 약관에 동의해주셔야 합니다"
    case alertSignUpComplete = "회원가입이 완료되었습니다.\n감사합니다!"
    case alertSignUpFailed = "회원가입을 완료하지 못했습니다."
    case alertAskSignUp = "%@ 아이디로 회원가입을 진행하시겠습니까?"
    case alertSocialAccountPwCannotChange = "소셜 로그인 계정은 비밀번호를 설정/변경할 수 없습니다"
    case alertAskChangePw = "비밀번호를 변경하시겠습니까?"
    case alertCostRange = "해당 사이즈의 기본 가격(%@)에서 [-50%% ~ +50%%]로 설정해야 합니다"
    case alertUnavailableCost = "잘못 설정된 가격이 있습니다. 다시 입력해주세요."
    case alertRequestSearchFailed = "의뢰를 검색할 수 없습니다."
    case alertFailedToSaveInfo = "입력한 정보를 저장하지 못했습니다."
    case alertNeedNewPw = "[비밀번호]를 입력해주세요"
    case alertNeedNewPwCheck = "[비밀번호 확인]을 입력해주세요"
    case alertFailedToRegisterPicture = "사진을 등록하지 못했습니다."
    case alertNeedHorizontalPicture = "가로 사진을 등록해주세요"
    case alertNeedVerticalPicture = "세로 사진을 등록해주세요"
    case alertNeedEnterStorageSize = "보관장소 크기를 입력해주세요"
    case alertNeedEnterStorageIntroduction = "소개글을 입력해주세요"
    case alertNeedRegisterPictureMin = "최소 1장의 사진을 등록해야 합니다"
    case alertTouchModifyButton = "오른쪽 하단의 '수정'버튼을 눌러주세요"
    case alertNeedRecommendUserCode = "추천인의 유저 코드를 입력해주세요"
    case alertRequestApproveSuccess = "보관파트너 승인을 요청했습니다. 최대 5분이내에 처리 완료 될 예정입니다."
    case alertRequestApproveFailed = "보관파트너 승인 요청을 완료하지 못했습니다."
    case alertNeedRegisterMainPicture = "대표 사진을 등록해주세요"
    case alertRequestWriteStoreSuccess = "매장 정보가 등록되었습니다.\n감사합니다."
    case alertFailedToGetBizInto = "사업자 정보를 받아오지 못했습니다."
    case alertRegisterMeritsSuccess = "보관 장점 등록 성공"
    case alertRegisterMeritsFailed = "보관 장점을 등록하지 못했습니다."
    case alertRegisterLuggageSuccess = "짐 보관 개수 등록 성공"
    case alertRegisterLuggageFailed = "짐 보관 개수를 등록하지 못했습니다."
    case alertRegisterCategoryFailed = "업종을 등록하지 못했습니다."
    case alertLoadCategoryFailed = "업종을 불러오지 못했습니다."
    case alertRegisterPrFailed = "소개글을 등록하지 못했습니다."
    case alertRegisterDayoff = "휴무일을 등록하지 못했습니다."
    case alertLoadDayoffFailed = "휴무일 정보를 불러오지못했습니다."
    case alertLoadOrdersFailed = "의뢰 목록을 불러오지 못했습니다."
    case alertLoadOrderFailed = "의뢰 정보를 불러오지 못했습니다."
    case alertEmptyOrder = "주문 정보가 없습니다."
    case alertLoadLuggagePicFailed = "의뢰 물풀 사진을 불러오지 못했습니다."
    case alertOrderUpdateFailed = "의뢰 진행 상황을 업데이트하지 못했습니다."
    case alertLoadCashupFailed = "정산 정보를 불러오지 못했습니다."
    case alertLoadProfilePicFailed = "프로필 사진을 불러오지 못했습니다."
    case alertRegisterProfilePicFailed = "프로필 사진을 등록하지 못했습니다."
    case alertNoIdMatchingWithEmail = "해당 이메일(%@)로 등록된 ID가 없습니다"
    case alertIdsMatchingWithEmail = "해당 이메일(%@)로 등록된 ID:"
    case alertInvalidLicenseNo = "유효하지않은 사업자등록번호 입니다."
    case alertNeedContactAuth = "연락처 인증이 필요합니다."
    case alertPictureSelectionErr = "사진 선택 오류"
    
    case sideMenuSection01 = "의뢰"
    case sideMenuSection02 = "기본 정보"
    case sideMenuSection03 = "기타"
    
    case sideMenu11 = "앱 가이드"
    case sideMenu12 = "유의사항"
    
    case terms01 = "이용약관"
    case terms02 = "개인정보 처리방침"
    case terms03 = "마케팅 정보 제공·이용 동의서"
    case termsAgree01 = "회원 약관 동의"
    case termsAgree02 = "개인정보 처리방침 동의"
    case termsAgree03 = "마케팅 정보 제공·이용 동의"
    
    case settingsSection01 = "보관사업자 활동"
    case settingsSection01Menu01 = "매장정보"
    
    case settingsSection02 = "사용자 설정"
    case settingsSection02Menu01 = "사업자 정보 입력"
    case settingsSection02Menu02 = "매장 정보 입력"
    
    case settingsSection03 = "내정보"
    case settingsSection03Menu01 = "정보 변경"
    
    case settingsSection04 = "고객센터"
    case settingsSection04Menu01 = "약관"
    case settingsSection04Menu02 = "문의하기"
    case settingsSection04Menu03 = "회사소개"
    
    case settingsSection05 = "버전 정보"
    
    case monday = "월"
    case tuesday = "화"
    case wendsday = "수"
    case thursday = "목"
    case friday = "금"
    case saturday = "토"
    case sunday = "일"
    
    case month01 = "1월"
    case month02 = "2월"
    case month03 = "3월"
    case month04 = "4월"
    case month05 = "5월"
    case month06 = "6월"
    case month07 = "7월"
    case month08 = "8월"
    case month09 = "9월"
    case month10 = "10월"
    case month11 = "11월"
    case month12 = "12월"
    
    case month = " 월"
    case day = " 일"
    case year = "년"
    
    case luggageS = "작은짐"
    case luggageM = "보통짐"
    case luggageL = "큰짐"
    case luggageXL = "대형짐"
    
    case sceneNameRegister = "보관정보 등록/수정"
    case sceneNameRegisterCost = "보관 가격 책정"
    
    case companyName = "주식회사 플래틱스"
    case businessNumberTitle = "사업자등록번호"
    case mainOrderNumberTitle = "통신판매번호"
    case registerEnquiry = "가입문의"
    case companyDesc = "주식회사 플래틱스는 통신판매중개자로서, 상품(서비스)/거래정보 및 거래와 과나련하여 통신파내 당사자의 고의 또는 과실로 소비자에게 발생하는 손해에대해 책임을 지지 않습니다. 상품(서비스) 및 거래에 대한 정확한 정보는 해당 판매자에게 직접 확인바랍니다."
    case compnayAddress = "서울특별시 강서구 하늘길 70, 한국공항공사 항공지원센터 2층 KACoon(가꾼) Office-G"
    case AllRightsReserved = "Copyright CARRIFREE All Rights Reserved."
    
    case appGuideStore01 = "회워가입 -> 로그인 후 메인화면의 왼쪽 상단 메뉴에서 [사업자 등록/수정]을 선택합니다"
    case appGuideStore02 = "[내정보]탭에서 사업자와 관련된 정보를 모두 입력합니다"
    case appGuideStore03 = "[사진]탭에서 보관 장소 사진을 업로드 합니다"
    case appGuideStore04 = "[쉬는날]탭에서 영업시간과 쉬는날을 등록합니다"
    case appGuideStore05 = "[가격]탭에서 보관 서비스의 단가를 책정합니다"
    case appGuideStore06 = "사업자 등록을 완료하면 캐리프리앱(사용자앱)에서 사용자들이 내 가게를 검색하고 물풀 보관을 의뢰할 수 있습니다. 접수된 보관 의뢰는 메인화면에 표시됩니다."
    case appGuideStore07 = "메인화면에서 의뢰를 선택하여 의뢰 진행사항을 확인하거나 완료할 수 있습니다"
    
    case needRegisterBiz = "사업자 등록 필요!"
    case needRegisterBizDesc = "보관파트너 서비스를 이용하시려면 사업자정보 및 매장정보를 입력해 주세요."
    
    case platformKakao = "카카오"
    case platformFacebook = "페이스북"
    case platformNaver = "네이버"
    case platformApple = "애플"
    case platformGoogle = "구글"
    
    
    /*
    var en: String {
        switch self {
        case .ok: return "확인"
        case .cancel: return "취소"
        case .yes: return "네"
        case .no: return "아니오"
        case .id: return "아이디"
        case .pw: return "비밀번호"
        case .findIDPW: return "ID/비밀번호 찾기"
        case .camera: return "카메라"
        case .signIn: return "로그인"
        case .signOut: return "로그아웃"
        case .signOutDone: return "로그아웃 되었습니다"
        case .signUp: return "회원가입"
        case .address: return "주소"
        case .searchAddress: return "주소 찾기"
        case .photo: return "사진"
        case .photoAlbum: return "사진 앨범"
        case .setMyInfo: return "내 정보 변경"
        case .copied: return "복사 됨"
        case .service: return "서비스"
        case .serviceRequestDate: return "서비스 신청 일시"
        case .storeService: return "보관 서비스"
        case .entrust: return "맡김"
        case .take: return "찾음"
        case .findId: return "아이디 찾기"
        case .findPw: return "비밀번호 찾기"
        case .findByEmail: return "이메일로 찾기"
        case .findByPhoneNum: return "휴대폰 번호로 찾기"
        case .storageOperAgree: return "보관사업자 약관동의"
        case .showTerms: return "약관 보기"
        case .save: return "저장"
        case .modify: return "수정"
        case .saveDone: return "저장되었습니다"
        case .saveFailed: return "저장 실패"
        case .plzTryAgain: return "다시 시도해주시기 바랍니다"
        case .registerWith01: return "로 등록"
        case .registerWith02: return "으로 등록"
        case .defaultCost: return "기본요금"
        case .extraCost: return "추가요금"
        case .size: return "사이즈"
        case .bizName: return "상호명"
        case .memberInfo: return  "회원 정보"
        case .bizCategory: return "업종"
        case .bizNo: return "사업자 번호"
        case .bizLicense: return "사업자 등록증"
        case .name: return "이름"
        case .name2: return "성명"
        case .startTime: return "맡기는 시간"
        case .endTime: return "찾는 시간"
        case .duringTotal: return "총 보관 시간"
        case .driver: return "운송자"
        case .customer: return "고객"
        case .completion: return "완료"
        case .storageInfo: return "보관장소 정보"
        case .eMail: return "이메일"
        case .bankAccountNum: return "계좌번호"
        case .addressDetail: return "상세주소"
        case .enterAddressDetail: return "상세주소 입력"
        case .introduceInfoText: return "소개글"
        case .introduceInfoTextPlaceHolder: return "상호 밑에 사업자의 소개부분에 들어갈 내용입니다. 서비스의 내용, 특징 등 고객에게 어필할 내용을 작성해보세요."
        case .workTime: return "활동 시간"
        case .selectBank: return "은행 선택"
        case .registerDayOffDefault: return "기본(토, 일, 국경일)"
        case .registerDayOffManual: return "수동선택(중복선택 가능)"
        case .registerDayOffAllHoliday: return "국경일 모두 쉬기"
        case .annouceBusiness: return "물품 보관/위수탁 사업 안내"
        case .storageDesc: return "짐 보관 장소의 역할로 매출액의 70%(제세공과금 정산 후)가 정산됩니다"
        case .consignmentStore: return "위수탁 창구"
        case .consignmentStoreDesc: return "운반 의뢰 고객이 짐맡김/찾음 장소 중 한 곳으로 지정시 해당 짐맡김/찾음 창구사용료 중 60%(제세공과금 정산 후)가 지급됩니다."
        case .cost: return "가격"
        case .cost2: return "금액"
        case .cost3: return "결제금액"
        case .cost4: return "추가금액"
        case .cost5: return "총 금액"
        case .cost6: return "환불금액"
        case .costDesc: return "보관 가격은 기본적으로 캐리프리에서 시세를 반영한 값을 제시합니다. 제시된 가격의 -50% ~ +50% 내에서 가격을 조정할 수 있습니다."
        case .seeMore: return "더보기"
        case .luggageInfo: return "짐정보"
        case .requests: return "요청사항"
        case .startStorage: return "보관 시작"
        case .endStorage: return "보관 종료"
        case .consignment: return "위수탁"
        case .storageRequestIsEmpty: return "보관 의뢰가 없습니다"
        case .carrierBaseRequestIsEmpty: return "위수탁 의뢰가 없습니다"
        case .someonesReqeust: return "[%@]님의 의뢰내용"
        case .someonesStartCarrierBaseRequest: return "[%@]님의 의뢰내용\n(물품 보관 후 운반 위탁)"
        case .someonesEndCarrierBaseRequest: return "[%@]님의 의뢰내용\n(운반된 물품 보관 후 고객에게 전달)"
        case .callToSomeone: return "[%@] 님에게 전화하시겠습니까?"
        case .storage: return "보관"
        case .inDelivery: return "이동 중"
        case .arrival: return "도착"
        case .cannotVerified: return "'%@'을(를) 확인할 수 없습니다"
        case .sendLuggage: return "물품 반출"
        case .totalSales: return "총 매출"
        case .annualSales: return "연 매출"
        case .monthlySales: return "월 매출"
        case .dailySales: return "일 매출"
        case .sales: return "매출액"
        case .profit: return "수령금액"
        case .excelDownloadDesc: return "세부 매출 내용은 엑셀 파일로 다운로드할 수 있습니다"
        case .excelDownload: return "엑셀 파일 다운로드"
        case .ordered: return "접수"
        case .requestSuccess: return "요청 성공"
        case .requestFailed: return "요청 실패"
        case .customerName: return "고객 이름"
        case .requestType: return "의뢰 방법"
        case .reply: return "댓글"
        case .verificationFailed01: return "본인인증에 실패했습니다"
        case .verificationFailed02: return "인증 실패"
        case .verificationSuccess01: return "본인인증 성공"
        case .verificationSuccess02: return "인증 성공"
        case .failedToWithdrawal: return "회원 탈퇴 실패"
        case .successToWithdrawal: return "회원 탈퇴가 완료되었습니다"
        case .withdrawal: return "회원 탈퇴"
        case .needSignIn: return "로그인이 필요합니다"
        case .csAnnounce: return "문의 메일 주소가 복사되었습니다.해당 메일 주소로 문의 내용을 보내주시기 바랍니다.\n감사합니다."
        case .requestList: return "의뢰 목록"
        case .noReviews: return "작성된 평가가 없습니다"
        case .needBizInfo: return "먼저 [기본 정보]를 입력해주세요"
        case .registerCost: return "가격등록"
        case .mustRegisterToRecieveRequest: return "아래 정보를 모두 등록해야 의뢰를 받을 수 있습니다"
        case .touchAndRegisterInfo: return "터치하여 정보 등록"
        case .todayExpectedSales: return "오늘 예상 매출"
        case .thisMonthSales: return "이번달 매출"
        case .reservationDate: return "예약일"
        case .during: return "보관시간"
        case .luggageCount: return "짐 갯수"
        case .requiredAppUpdate: return "앱 업데이트가 필요합니다"
        case .moveToStore: return "스토어로 이동"
        case .accountHolder: return "예금주명"
        case .businessApproval: return "사업자 승인"
        case .waitingBusinessApproval: return "사업자 승인 대기중"
        case .registerStoragePictures: return "보관장소 사진 등록"
        case .pictureStorageFrontBack: return "보관장소 전면/후면 사진 1장이상"
        case .pictureStorageNormal: return "보관장소 사진 1장이상"
        case .pictureStorageMain: return "메인으로 표시할 사진\n(보관소 전면 사진을 등록해주세요)"
        case .registration: return "등록"
        case .socialAccountDesc: return "소셜 로그인(%@) 계정입니다"
        case .searchStorageRequest: return "보관 의뢰 검색"
        case .searchCarrierBaseRequest: return "위수탁 의뢰 검색"
        case .search: return "검색"
        case .requestNo: return "주문번호"
        case .passwordRule: return "필수: 6~12자리 영문, 숫자, !@#$%^&*"
        case .passwordCheck: return "비밀번호 확인"
        case .registrationComplete: return "등록 완료"
        case .changePassword: return "비밀번호 변경"
        case .bank: return "은행"
        case .contactNum: return "연락처"
        case .contactNumOther: return "비상 연락처"
        case .required: return "필수"
        case .enterBankAccountInfo: return "계좌 정보 입력"
        case .horizontal: return "가로"
        case .vertical: return "세로"
        case .height: return "높이"
        case .signUpEmail: return "회원가입시 작성한 이메일"
        case .emailVerificationCode: return "이메일로 발송된 인증 코드"
        case .verificationCode: return "인증 코드"
        case .sendVerificationCode: return "인증 코드 발송"
        case .needNewPw: return "비밀번호가 기억나지 않으면 새비밀번호를 설정해야합니다."
        case .signInWithSNSAccount: return "SNS 계정으로 로그인"
        case .normalSignUp: return "일반(캐리프리) 회원가입"
        case .chooseSignUp: return "가입 방식 선택"
        case .terms: return "이용 약관"
        case .see: return "보기"
        case .duplicationCheck: return "중복 확인"
        case .recommedCode: return "추천 코드"
        case .optional: return "선택 사항"
        case .send: return "발송"
        case .verification: return "인증"
        case .userCode: return "유저 코드"
        case .dayInCostTitle: return "1일 이내 요금"
        case .dayInCostDesc01: return "기본요금: 4시간 / 추가요금: 1시간"
        case .dayInCostDesc02: return "(처음 4시간 기본 요금 적용 후 1시간당 추가요금 발생)"
        case .dayOverCostTitle: return "1일 이후 요금"
        case .dayOverCostDesc: return "처음 보관한 시간으로부터 24시간이 지난 후 1일 단위로 발생하는 요금"
        case .carrifreeCostTtile: return "가격 설정 기준"
        case .extraCostDesc01: return "고객이 의뢰 종료 시간보다 늦게 물품을 찾으러 오는 경우 책정한 보관 비용에 따라 초과된 금액을 고객에게 요청할 수 있습니다. 캐리프리는 초과금에 대해 앱을 통한 추가 결제를 유도하지 않으므로 고객에게 현금 또는 보관소내 결제 단말기(POS, 캐리프리 키오스크 등)를 통해 초과금 지급을 요구해 주시기 바랍니다."
        case .extraCostDesc02: return "위수탁 창구 역할로 짐을 맡은 경우 물품이 1일이내에 반출되면 보관 비용을 별도로 청구할 수 없습니다. 1일을 경과하는 경우 책정한 보관비용에 따라 초과된 금액을 고객에게 요청할 수 있습니다."
        case .extraCostTitle: return "초과 금액이 발생한 경우"
        case .storagePicture: return "보관소 사진"
        case .holiday: return "쉬는날"
        case .storageCost: return "보관 단가"
        case .bizInfo: return "사업자 정보"
        case .review: return "리뷰"
        case .settings: return "설정"
        case .orderStatusPurchasedDesc: return "보관이 진행되면 ‘보관중’으로 넘어갑니다.\n완료 또는 취소된 보관 내용은 ‘처리완료’로 넘어갑니다."
        case .orderStatusEntrustDesc: return "보관이 완료되면 ‘처리완료’로 넘어갑니다.\n초과 발생금액은 직접 정산하시기 바랍니다."
        case .orderStatusTakeDesc: return "처리가 완료된 내역을 표시합니다."
        case .orderStatusPurchasedTitle: return "주문대기"
        case .orderStatusEntrustTitle: return "보관중"
        case .orderStatusTakeTitle: return "처리완료"
        case .runAgain: return "앱을 종료한 후 다시 실행해주시기 바랍니다."
        case .socialSignInFailed: return "소셜 계정 로그인 실패"
        case .changeBizInfo: return "사업자 정보 변경"
        case .helloCarrifree: return "안녕하세요.\n캐리프리입니다."
        case .needCarrifreeStorageSignIn: return "보관파트너 전용 서비스를 위해 로그인 해주세요."
        case .bizInfoChanged: return "사업자 정보가 변경되었습니다."
        case .approvalRequestDone: return "보관 파트너 승인을 요청했습니다.\n감사합니다."
        case .meritsPlaceholder: return "매장의 특별한 점이 있다면 적어주세요."
        case .canChangePw: return "비밀번호를 변경할 수 있습니다."
        case .thisMonthSalesTitle: return "이번달 수입은\n%@\n입니다."
        case .seeDetail: return "상세내역보기"
        case .needRegistrationTitle: return "아직 업체 정보가 등록되지 않았습니다.\n정보입력 후 활동이 가능합니다."
        case .registerInfo: return "정보 등록하기"
        case .guide: return "이용 안내"
        case .guideDesc: return "캐리프리 보관파트너를 위한 앱\n이렇게 사용해 보세요!"
        case .salesDetailBtnTitle: return "상세내역은 아래 버튼을 눌러 확인하세요."
        case .writeBizInfo: return "사업자정보 입력"
        case .writeName: return "이름 입력"
        case .nameWarning: return "불건전한 업체 이름은 승인처리가안될 수 있습니다."
        case .contactOption: return "‘-’를 제외하고 숫자만 입력"
        case .requestAuth: return "인증요청"
        case .authNo: return "인증번호"
        case .checkAuth: return "인증 확인"
        case .authComplete: return "인증완료"
        case .postalCode: return "우편번호"
        case .findPostalCode: return "우편번호찾기"
        case .bizAddress: return "사업장 주소"
        case .bankAccountDesc: return "계좌번호 (‘-’없이 입력)"
        case .needFile: return "제출서류를 제출해주세요."
        case .addBizLicense: return "사업자등록증 추가"
        case .addBizLicenseDesc: return "최근 발급일 6개월 이내"
        case .addBankbook: return "통장사본 추가"
        case .addBankbookDesc: return "입력하신 계좌와 동일한 통장사본"
        case .beforeRegistration: return "등록 전 확인해주세요."
        case .beforeRegistrationDesc: return """
        ・ 타인의 명의로 가입한 경우 승인처리가 완료되지
           않습니다.
        ・ 한번 승인 된 사업자 및 결제정보를 변경 할 경우
           다시 재심사를 진행하여야 합니다.
        """
        case .registrationWating: return "최대 5분이내에 처리 완료 될 예정입니다."
        case .requestRegistration: return "보관파트너 승인 요청"
        case .validLicneseNo: return "유효한 사업자등록번호 입니다."
        case .enterStoreInfo: return "매장정보 입력"
        case .setVisible: return "보관사업자 게시 상태 설정"
        case .visible: return "노출"
        case .invisible: return "비노출"
        case .visibleDesc: return "영업이 바쁘거나 갑작스럽게 영업이 어려운 경우 ‘비노출’로 설정하시면 사용자앱에서 검색시 노출되지 않습니다."
        case .registerStorePic: return "매장사진을 등록해주세요.(최대 10개)"
        case .registerStorePicDesc: return "버튼을 눌러 매장사진을 등록하세요. 대표사진 1개는 등록되어야 매장 정보를 노출시킬 수 있습니다."
        case .registerStoreInfo: return "매장정보 등록/수정"
        case .registerWorkTime: return "매장 운영시간을 등록해주세요."
        case .opentime: return "시작시간"
        case .closetime: return "종료시간"
        case .enterPr: return "매장 소개글을 적어주세요."
        case .enterLuggagesTitle: return "짐 보관은 최대 몇개까지 가능하신가요?"
        case .enterLuggages: return "보관 가능한 짐 개수를 입력해주세요"
        case .wrongLuggages: return "짐 보관 수량을 올바르게 입력해주세요."
        case .ea: return "개"
        case .enterMerits: return "보관 장점을 선택하세요."
        case .emptyMerits: return "보관 장점을 1개 이상 선택해주세요"
        case .enterCosts: return "보관가격을 설정해주세요."
        case .usingCarrifreeCosts: return "캐리프리 시세 반영"
        case .needDefaultSotrePic: return "업체(매장) 사진을 1장 이상 등록해주세요"
        case .wrongWorktime: return "근무 시간을 올바르게 입력해주세요"
        case .wrongCosts: return "가격을 올바르게 설정해주세요."
        case .registerStore: return "매장정보 등록"
        case .needPhotoAccessPermission: return "사진 접근 권한이 필요합니다. '확인'을 선택하면 사진 접근 설정 화면으로 이동합니다."
        case .notApproved: return "미승인"
        case .approvalComplete: return "승인완료"
        case .orderBegin: return "짐보관\n서비스가\n시작되었습니다."
        case .orderBeginDesc: return "짐보관 서비스가 시작되었으며, 진행중인 내역은 메뉴바 ‘보관중’에서 다시 확인하실 수 있습니다."
        case .orderComplete: return "짐보관\n서비스가\n완료되었습니다."
        case .orderCompleteDesc: return "짐보관이 완료되었료습니다. 완료된 주문내역은 [처리완료]에서 다시 확인이 가능합니다."
        case .moveToRegistration: return "사업자/매장 정보 입력하기"
        case .backToContent: return "다시 확인"
        case .notYetDesc: return "파트너님은\n서비스 이용을\n할 수 없습니다."
        case .askOrderCheck: return "파트너님\n주문서를 확인\n하셨나요?"
        case .needOrderCheck: return "고객의 정보와 보관할 짐의 이미지가 주문서와 일치하는지 다시 한번 확인 해주시기 바랍니다."
        case .goOrder: return "보관 진행"
        case .orderDone: return "보관 완료"
        case .canceledOrder: return "취소된 주문입니다."
        case .vat: return "부가세 포함"
        case .payDirect: return "직접정산"
        case .refundDone: return "환불완료"
        case .autoRefund: return "자동환불"
        case .whoOrdered: return "주문자"
        case .hour: return "시간"
        case .all: return "전체"
        case .enterNameOrOrderNo: return "'고객명' 혹은 '주문번호' 입력."
        case .wrongOrderInfo: return "잘못된 의뢰 정보입니다."
        case cashup = "정산"
        case showList = "목록보기"
        case orderCount = "보관건수"
        case salesDuration = "매출기준"
        case cashupInfo = "정산내역"
        case selectMonth = "월 선택"
        case duration = "기간"
        case storeInfo = "매장 정보"
        
        case .platformKakao: return "카카오"
        case .platformFacebook: return "페이스북"
        case .platformNaver: return "네이버"
        case .platformApple: return "애플"
        case .platformGoogle: return "구글"
        case .cashup: return "정산"
            
        case .alertSendEmailVerificationCode: return "이메일로 인증 코드가 발급되었습니다. 확인 후 인증 코드를 입력해주시기 바랍니다."
        case .alertRetryAddress: return "주소 찾기에서 오류가 발생했습니다. 다시 시도해주시기 바랍니다."
        case .alertNotFountLatLng: return "주소와 일치하는 위도/경도 좌표를 찾지 못했습니다. 다시 시도해주시기 바랍니다."
        case .alertSelectBank: return "은행을 선택해주세요"
        case .alertSelectStoreCategory: return "업종을 선택해주세요"
        case .alertEnterBizName: return "업체명을 입력해주세요"
        case .alertEnterBizAddress: return "사업장 주소를 입력해주세요"
        case .alertEnterAddressDetail: return "상세주소를 입력해주세요"
        case .alertEnterBizNo: return "사업자등록번호를 입력해주세요"
        case .alertEnterBankAccount: return "정산받을 계좌번호를 입력해주세요"
        case .alertEnterPhone: return "연락처를 입력해주세요"
        case .alertSelectPicture: return "사진을 선택해주세요"
        case .alertFailedToLoadCost: return "요금 정보를 받아오지 못했습니다"
        case .alertCannotYetStorage: return "아직 보관할 수 없습니다"
        case .alertCannotYetSend: return "아직 반출할 수 없습니다"
        case .alertAcceptRequest: return "[%@]님의 의뢰를 수락하시겠습니까?"
        case .alertSendLuggage: return "[%@]님에게 물품을 전달하시겠습니까?"
        case .alertCannotCheckUserPw: return "고객님의 비밀번호를 확인할 수 없습니다"
        case .alertFailedToLoadReview: return "리뷰를 불러오지 못했습니다"
        case .alertFailedToRegisterReply: return "댓글을 등록하지 못했습니다"
        case .alertWithdrawal: return "회원 탈퇴시 모든 정보가 삭제되며,\n이후 복구가 불가능합니다\n탈퇴를 진행하시겠습니까?"
        case .alertNeedAgreeForChangePw: return "핸드폰 번호를 변경하려면 [%@]에 동의해주시기 바랍니다"
        case .alertAskChangePhone: return "핸드폰 번호를 변경하시겠습니까?"
        case .alertNeedTerms02: return "개인정보 처리방침에 동의해주시기 바랍니다"
        case .alertLoadBasicCostFailed: return "기본 가격 정보를 불러오지 못했습니다."
        case .alertLoadCostFailed: return "내 가격 정보를 불러오지 못했습니다."
        case .alertRegisterCostSuccess: return "보관 가격 등록 완료"
        case .alertRegisterCostFailed: return "가격을 등록하지 못했습니다"
        case .alertUpdateInfoLoadFailed: return "업데이트 정보를 불러오지 못했습니다."
        case .alertEnterAccountHolder: return "예금주명을 입력해주세요"
        case .alertRequestApproval: return """
        아직 캐리프리 사업자로 승인되지 않았습니다.
        
        [기본 정보]
        [보관소 사진]
        [쉬는날]
        [보관 단가]
        
        항목을 모두 입력해야 사업자 승인이 이루어집니다. 승인은 1~2일이 소요되며 승인이 완료된 후 고객의 보관 의뢰를 받을 수 있습니다.
        """
        case .alertIncorrectPasswordLength: return "비밀번호는 6자 이상 12자 이하여야 합니다"
        case .alertNeedAlphabet: return "영문이 1개 이상 포함되어야 합니다"
        case .alertNeedNumber: return "숫자가 1개 이상 포함되어야 합니다"
        case .alertNeedSpecialChar: return "특수문자가 1개 이상 포함되어야 합니다"
        case .alertPasswordAvailable: return "사용 가능한 비밀번호입니다"
        case .alertNoAvailableId: return "가입할 수 없는 아이디 입니다"
        case .alertSuccessToSendCode: return "코드 발급 성공"
        case .alertFailedToSendCode: return "코드 발급 실패"
        case .alertSuccessToFindId: return "아이디 찾기 성공"
        case .alertNeedId: return "아이디를 입력해주세요"
        case .alertNeedEmail: return "이메일을 입력해주세요"
        case .alertNeedVerificationCode: return "인증 번호를 입력해주세요"
        case .alertNeedPw: return "비밀번호를 입력해주세요"
        case .alertPwNotMatch: return "비밀번호가 일치하지 않습니다"
        case .alertChangePwComplete: return "비밀번호 변경 완료"
        case .alertFailedToChangePw: return "비밀번호를 변경하지 못했습니다"
        case .alertSignInFailed: return "로그인 실패"
        case .alertSignInSuccess: return "로그인 성공"
        case .alertWelcome: return "%@님 환영합니다  : )"
        case .alertAskSignIn: return "%@ 아이디로 로그인하시겠습니까?"
        case .alertIdLengthMin: return "아이디는 최소 5자 이상이어야 합니다"
        case .alertAvailableId: return "사용 가능한 아이디입니다"
        case .alertNeedName: return "이름을 입력해주세요"
        case .alertNeedIdDuplicationCheck: return "아이디 중복 확인이 필요합니다"
        case .alertUnavailablePw: return "사용할 수 없는 비밀번호 입니다"
        case .alertNeedEmailVerification: return "이메일 인증을 진행해주세요"
        case .alertNeedAgreeAllTerms: return "모든 약관에 동의해주셔야 합니다"
        case .alertSignUpComplete: return "회원가입이 완료되었습니다.\n감사합니다!"
        case .alertSignUpFailed: return "회원가입을 완료하지 못했습니다."
        case .alertAskSignUp: return "%@ 아이디로 회원가입을 진행하시겠습니까?"
        case .alertSocialAccountPwCannotChange: return "소셜 로그인 계정은 비밀번호를 설정/변경할 수 없습니다"
        case .alertAskChangePw: return "비밀번호를 변경하시겠습니까?"
        case .alertCostRange: return "해당 사이즈의 기본 가격(%@)에서 [-50%% ~ +50%%]로 설정해야 합니다"
        case .alertUnavailableCost: return "잘못 설정된 가격이 있습니다. 다시 입력해주세요."
        case .alertRequestSearchFailed: return "의뢰를 검색할 수 없습니다."
        case .alertFailedToSaveInfo: return "입력한 정보를 저장하지 못했습니다."
        case .alertNeedNewPw: return "[비밀번호]를 입력해주세요"
        case .alertNeedNewPwCheck: return "[비밀번호 확인]을 입력해주세요"
        case .alertFailedToRegisterPicture: return "사진을 등록하지 못했습니다."
        case .alertNeedHorizontalPicture: return "가로 사진을 등록해주세요"
        case .alertNeedVerticalPicture: return "세로 사진을 등록해주세요"
        case .alertNeedEnterStorageSize: return "보관장소 크기를 입력해주세요"
        case .alertNeedEnterStorageIntroduction: return "소개글을 입력해주세요"
        case .alertNeedRegisterPictureMin: return "최소 1장의 사진을 등록해야 합니다"
        case .alertTouchModifyButton: return "오른쪽 하단의 '수정'버튼을 눌러주세요"
        case .alertNeedRecommendUserCode: return "추천인의 유저 코드를 입력해주세요"
        case .alertRequestApproveSuccess: return "보관파트너 승인을 요청했습니다. 최대 5분이내에 처리 완료 될 예정입니다."
        case .alertRequestApproveFailed: return "보관파트너 승인 요청을 완료하지 못했습니다."
        case .alertNeedRegisterMainPicture: return "대표 사진을 등록해주세요"
        case .alertRequestWriteStoreSuccess: return "매장 정보가 등록되었습니다.\n감사합니다."
        case .alertFailedToGetBizInto: return "사업자 정보를 받아오지 못했습니다."
        case .alertRegisterMeritsSuccess: return "보관 장점 등록 성공"
        case .alertRegisterMeritsFailed: return "보관 장점을 등록하지 못했습니다."
        case .alertRegisterLuggageSuccess: return "짐 보관 개수 등록 성공"
        case .alertRegisterLuggageFailed: return "짐 보관 개수를 등록하지 못했습니다."
        case .alertRegisterCategoryFailed: return "업종을 등록하지 못했습니다."
        case .alertLoadCategoryFailed: return "업종을 불러오지 못했습니다."
        case .alertRegisterPrFailed: return "소개글을 등록하지 못했습니다."
        case .alertRegisterDayoff: return "휴무일을 등록하지 못했습니다."
        case .alertLoadDayoffFailed: return "휴무일 정보를 불러오지못했습니다."
        case .alertLoadOrdersFailed: return "의뢰 목록을 불러오지 못했습니다."
        case .alertLoadOrderFailed: return "의뢰 정보를 불러오지 못했습니다."
        case .alertEmptyOrder: return "주문 정보가 없습니다."
        case .alertLoadLuggagePicFailed: return "의뢰 물풀 사진을 불러오지 못했습니다."
        case .alertOrderUpdateFailed: return "의뢰 진행 상황을 업데이트하지 못했습니다."
        case .alertLoadCashupFailed: return "정산 정보를 불러오지 못했습니다."
        case .alertLoadProfilePicFailed: return "프로필 사진을 불러오지 못했습니다."
        case .alertRegisterProfilePicFailed: return "프로필 사진을 등록하지 못했습니다."
        case .alertNoIdMatchingWithEmail: return "해당 이메일(%@)로 등록된 ID가 없습니다"
        case .alertIdsMatchingWithEmail: return "해당 이메일(%@)로 등록된 ID:"
        case .alertInvalidLicenseNo: return "유효하지않은 사업자등록번호 입니다."
        case .alertNeedContactAuth: return "연락처 인증이 필요합니다."
        case .alertPictureSelectionErr: return "사진 선택 오류"
            
        case .sideMenuSection01: return "의뢰"
        case .sideMenuSection02: return "기본 정보"
        case .sideMenuSection03: return "기타"
            
        case .sideMenu11: return "앱 가이드"
        case .sideMenu12: return "유의사항"
            
        case .terms01: return "이용약관"
        case .terms02: return "개인정보 처리방침"
        case .terms03: return "마케팅 정보 제공·이용 동의서"
        case .termsAgree01: return "회원 약관 동의"
        case .termsAgree02: return "개인정보 처리방침 동의"
        case .termsAgree03: return "마케팅 정보 제공·이용 동의"
            
        case .settingsSection01: return "보관사업자 활동"
        case .settingsSection01Menu01: return "매장정보"

        case .settingsSection02: return "사용자 설정"
        case .settingsSection02Menu01: return "사업자 정보 입력"
        case .settingsSection02Menu02: return "매장 정보 입력"

        case .settingsSection03: return "내정보"
        case .settingsSection03Menu01: return "정보 변경"

        case .settingsSection04: return "고객센터"
        case .settingsSection04Menu01: return "약관"
        case .settingsSection04Menu02: return "문의하기"
        case .settingsSection04Menu03: return "회사소개"
        
        case .settingsSection05: return "버전 정보"
            
        case .monday: return "월"
        case .tuesday: return "화"
        case .wendsday: return "수"
        case .thursday: return "목"
        case .friday: return "금"
        case .saturday: return "토"
        case .sunday: return "일"
            
        case .month: return " 월"
        case .day: return " 일"
        case .year: return "년"
            
        case .luggageS: return "작은짐"
        case .luggageM: return "보통짐"
        case .luggageL: return "큰짐"
        case .luggageXL: return "대형짐"
            
        case .sceneNameRegister: return "보관정보 등록/수정"
        case .sceneNameRegisterCost: return "보관 가격 책정"
            
        case .companyName: return "주식회사 플래틱스"
        case .businessNumberTitle: return "사업자등록번호"
        case .mainOrderNumberTitle: return "통신판매번호"
        case .registerEnquiry: return "가입문의"
        case .companyDesc: return "주식회사 플래틱스는 통신판매중개자로서, 상품(서비스)/거래정보 및 거래와 과나련하여 통신파내 당사자의 고의 또는 과실로 소비자에게 발생하는 손해에대해 책임을 지지 않습니다. 상품(서비스) 및 거래에 대한 정확한 정보는 해당 판매자에게 직접 확인바랍니다."
        case .compnayAddress: return "서울특별시 강서구 하늘길 70, 한국공항공사 항공지원센터 2층 KACoon(가꾼) Office-G"
        case .AllRightsReserved: return "Copyright CARRIFREE All Rights Reserved."
            
        case .thanksToApple: return "이 앱은 Apple의 앱 심사/개발 지침을 준수하며 Xcode로 개발되었습니다."
        case .thanksToFirebase: return "FCM(Firebase Cloud Messaging)을 사용하여 PUSH 알림 서비스를 구현했습니다."
        case .thanksToIcon8: return "메뉴 아이콘 일부를 Icons8에서 제공하는 이미지를 사용했습니다."
        case .thanksToAlamofire: return "서버와의 통신을 위해 Alamofire 라이브러리를 사용했습니다."
        case .thanksToFacebook: return "소셜 로그인을 위해 Facebook 로그인 라이브러리를 사용했습니다."
        case .thanksToKakao: return "소셜 로그인과 주소 검색을 위해 Kakao로그인 라이브러리와 주소 API를 사용했습니다."
        case .thanksToNaver: return "소셜 로그인을 위해 Naver 로그인 라이브러리를 사용했습니다."
            
        case .appGuideStore01: return "회워가입 -> 로그인 후 메인화면의 왼쪽 상단 메뉴에서 [사업자 등록/수정]을 선택합니다"
        case .appGuideStore02: return "[내정보]탭에서 사업자와 관련된 정보를 모두 입력합니다"
        case .appGuideStore03: return "[사진]탭에서 보관 장소 사진을 업로드 합니다"
        case .appGuideStore04: return "[쉬는날]탭에서 영업시간과 쉬는날을 등록합니다"
        case .appGuideStore05: return "[가격]탭에서 보관 서비스의 단가를 책정합니다"
        case .appGuideStore06: return "사업자 등록을 완료하면 캐리프리앱(사용자앱)에서 사용자들이 내 가게를 검색하고 물풀 보관을 의뢰할 수 있습니다. 접수된 보관 의뢰는 메인화면에 표시됩니다."
        case .appGuideStore07: return "메인화면에서 의뢰를 선택하여 의뢰 진행사항을 확인하거나 완료할 수 있습니다"
            
        case .needRegisterBiz: return "사업자 등록 필요!"
        case .needRegisterBizDesc: return "보관파트너 서비스를 이용하시려면 사업자정보 및 매장정보를 입력해 주세요."

        case .storageGuidelines: return """
        보관사업자님은 반드시 다음사항을 꼭 지켜주세요.
        
        1.고객이 물품을 의뢰 할 때 : 태그스티거작성을 요청하고 고객이 직접 잠금부분에 태그로 밀봉한 후 사진을 찍어서 전송 후 물품을 받아서 보관
        
        2.의뢰 물품을 운송자에게 넘길 때 : 운송자 아이디 확인과 운송사업자가 찍은 사진이 전송되어 물품상황이 ‘완료＇로 넘어간 후 물품 전달
        
        3.운송사업자가 의뢰물품을 갖고 올 때 : 태그 및 물품의 손상여부 확인 후 사진을 찍어서 전송 후 물품을 받아서 보관
        
        4.보관 물품을 의뢰인에게 넘길 때 : 고객이 찾기용 QR 코드 입력이나 비밀번호를 입력한 후 물품을 전달
        
        위의 내용이 지켜지지 않은 상황에서 발생하는 물품의 파손, 분실시에는 보관사업자에게 법적 보상 책임이 있습니다.
        """
            
        case .providerRuleTitle: return "보관사업자님은 다음 사항을 반드시 지켜주세요"
        case .providerRuleDesc: return """
        1. 고객이 물품을 의뢰 할때: 태그 스티커 작성을 요청하고 고객이 직접 잠금 부분부터 태그를 밀봉한 후 물품을 받아서 보관\n\n
        2. 의뢰 물품을 운송자에게 넘길때: 운송자 아이디를 확인하고 운송자가 물품 사진을 찍은 후 물품 상황이 완료로 변경되면 물품 전달
        """
        }
    }
     */
}
